export type StaffMember = {
  name: string;
  role: string;
  qualification?: string;
  group: "leadership" | "admin" | "faculty";
};

export const staff: StaffMember[] = [
  {
    name: "Sartaj Mir",
    role: "Principal",
    qualification:
      "M.A. Public Administration, M.A. Political Science, PG Diploma in Guidance & Counselling, B.Ed., PGDCA",
    group: "leadership",
  },
  {
    name: "Raja Zubair Ahmed",
    role: "Director",
    group: "leadership",
  },
  {
    name: "Dr. Asma",
    role: "Doctor",
    qualification: "MBBS",
    group: "admin",
  },
  {
    name: "G.M. Zargar",
    role: "Office Superintendent",
    qualification: "B.A.",
    group: "admin",
  },
  {
    name: "Gagandeep Kour",
    role: "Human Resource Manager",
    qualification: "MBA, M.A. English, B.Ed.",
    group: "admin",
  },
  {
    name: "Gurpreet Singh",
    role: "Transport Supervisor",
    qualification: "B.Tech",
    group: "admin",
  },
  {
    name: "Ifra Mushtaq Moon",
    role: "Front Desk Executive",
    qualification: "BJMC, MAMCJ",
    group: "admin",
  },
  {
    name: "Iqbal Rasheed Khan",
    role: "Transport Manager",
    qualification: "B.A.",
    group: "admin",
  },
  {
    name: "Mahpara Ashraf",
    role: "Housekeeping Supervisor",
    qualification: "M.A. English, B.Ed.",
    group: "admin",
  },
  {
    name: "Mehru Khan",
    role: "Office Clerk",
    qualification: "B.Tech (I.T.)",
    group: "admin",
  },
  {
    name: "Nadia Altaf",
    role: "Front Desk Executive",
    qualification: "M.Sc. Geography",
    group: "admin",
  },
  {
    name: "Sajid Rashid",
    role: "Accountant",
    qualification: "B.Com, M.Com, Dip. in Computer Science, Dip. in Tally Prime",
    group: "admin",
  },
  {
    name: "Samreen Farooq",
    role: "Front Desk Executive",
    qualification: "M.Sc. EVS",
    group: "admin",
  },
  {
    name: "Tariq Ahmad Waza",
    role: "IT Manager",
    qualification: "BCA, MCA, PG DWD",
    group: "admin",
  },
  {
    name: "Pallabi Tiwary",
    role: "Coordinator",
    qualification: "M.Com, B.Ed.",
    group: "faculty",
  },
  {
    name: "Haika",
    role: "Coordinator, Exams",
    qualification: "M.Sc. Chemistry, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Aabid Hussain",
    role: "TGT",
    qualification: "M.Sc. Mathematics, B.Ed., M.Ed., M.A. English, CTET",
    group: "faculty",
  },
  {
    name: "Aamir Imtiyaz",
    role: "TGT",
    qualification: "B.Tech (Mechanical), M.Tech (Thermal Engineering)",
    group: "faculty",
  },
  {
    name: "Abdur Rehman Khan",
    role: "TGT",
    qualification: "M.A. English, PGCTL",
    group: "faculty",
  },
  {
    name: "Aimen Nazir",
    role: "Librarian",
    qualification: "M.LIS",
    group: "faculty",
  },
  {
    name: "Ambreen Hafiz",
    role: "PRT",
    qualification: "M.Sc. Microbiology, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Aqsa Fayaz",
    role: "Mother Teacher",
    qualification: "M.Sc. Bio Chemistry, B.Ed.",
    group: "faculty",
  },
  {
    name: "Arzeen Jeelani",
    role: "PRT",
    qualification: "M.Sc. Botany, B.Ed.",
    group: "faculty",
  },
  {
    name: "Baseerat Mehraj",
    role: "TGT",
    qualification: "M.A. Economics, M.Phil",
    group: "faculty",
  },
  {
    name: "Bisma Rasheed",
    role: "Mother Teacher",
    qualification: "M.A. History, B.Ed.",
    group: "faculty",
  },
  {
    name: "Dr. Aejaz Ali Malla",
    role: "PET",
    qualification: "M.P.Ed, Ph.D. (Physical Education)",
    group: "faculty",
  },
  {
    name: "Furkan Nisar",
    role: "TGT",
    qualification: "M.A.",
    group: "faculty",
  },
  {
    name: "Hadia Hussain",
    role: "PRT",
    qualification: "M.A. Economics, B.Ed.",
    group: "faculty",
  },
  {
    name: "Huma Malik",
    role: "Librarian",
    qualification: "M.A., M.Sc., M.LIS, M.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Humaira Akhter",
    role: "Mother Teacher",
    qualification: "M.A. Economics, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Humza Mohammad Zargar",
    role: "Mother Teacher",
    qualification: "M.A. English, B.Ed.",
    group: "faculty",
  },
  {
    name: "Insha Nissar",
    role: "PRT",
    qualification: "M.Sc. Zoology, B.Ed., CTET, SET",
    group: "faculty",
  },
  {
    name: "Insha Yaseen",
    role: "Mother Teacher",
    qualification: "M.Sc. EVS, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Iram Mehboob",
    role: "PRT",
    qualification: "M.Sc. Zoology, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Irfan Ahmad Bhat",
    role: "TGT",
    qualification: "M.Sc. Mathematics, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Iyman Imtiyaz Khan",
    role: "PRT",
    qualification: "M.Sc. Zoology, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Jamsheeda",
    role: "PET",
    qualification: "B.P.Ed, NS-NIS (Handball)",
    group: "faculty",
  },
  {
    name: "Jasia Bhat",
    role: "PRT",
    qualification: "M.A. Sociology, B.Ed., M.Ed. (Gold Medalist), CTET",
    group: "faculty",
  },
  {
    name: "Jyoti Devi",
    role: "TGT",
    qualification: "M.A., B.Ed.",
    group: "faculty",
  },
  {
    name: "Khalida Firdous",
    role: "PRT",
    qualification: "M.A. Urdu, B.Ed.",
    group: "faculty",
  },
  {
    name: "Komal Preet Kour",
    role: "Art and Craft Teacher",
    qualification: "M.Sc. Statistics",
    group: "faculty",
  },
  {
    name: "Madiha Mohammad Zargar",
    role: "Mother Teacher",
    qualification: "M.A. Anthropology, B.Ed.",
    group: "faculty",
  },
  {
    name: "Madihah Zehra",
    role: "PRT",
    qualification: "M.Sc. Zoology, B.Ed.",
    group: "faculty",
  },
  {
    name: "Mehraj U Din Bhat",
    role: "PRT",
    qualification: "M.A., B.Ed.",
    group: "faculty",
  },
  {
    name: "Mehroosha Sadiq",
    role: "PRT",
    qualification: "M.A. Hindi",
    group: "faculty",
  },
  {
    name: "Mehwish Ramzan",
    role: "Mother Teacher",
    qualification: "M.Sc. Zoology",
    group: "faculty",
  },
  {
    name: "Mehwish Showkat",
    role: "PRT",
    qualification: "B.Tech",
    group: "faculty",
  },
  {
    name: "Misbah Rashid",
    role: "Mother Teacher",
    qualification: "B.Tech",
    group: "faculty",
  },
  {
    name: "Mohammad Altaf Shagoo",
    role: "Music Teacher",
    qualification: "B.A.",
    group: "faculty",
  },
  {
    name: "Mohammad Amin Dar",
    role: "Martial Arts Coach",
    qualification: "Diploma in Martial Arts, Black Belt 4th DAN",
    group: "faculty",
  },
  {
    name: "Mohammad Sultan Khan",
    role: "TGT",
    qualification: "M.A. Urdu, M.A. Education, B.Ed., M.Ed.",
    group: "faculty",
  },
  {
    name: "Monisa Bashir",
    role: "Mother Teacher",
    qualification: "M.Sc. Forestry",
    group: "faculty",
  },
  {
    name: "Navneet Kour",
    role: "PRT",
    qualification: "BCA, MCA",
    group: "faculty",
  },
  {
    name: "Nazima Mushtaq",
    role: "PRT",
    qualification: "M.A. English, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Nirmal Adak",
    role: "TGT",
    qualification: "B.Tech, B.Ed., M.A. English",
    group: "faculty",
  },
  {
    name: "Nuzhat Nabi",
    role: "PRT",
    qualification: "M.Sc. Zoology, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Ovase Ahmad",
    role: "Music Teacher",
    qualification: "B.A.",
    group: "faculty",
  },
  {
    name: "Rabia Majeed",
    role: "Mother Teacher",
    qualification: "M.A. History, B.Ed., CTET",
    group: "faculty",
  },
  {
    name: "Rafaqat Ahmad Paray",
    role: "TGT",
    qualification: "M.A. History, M.A. Political Science, B.Ed.",
    group: "faculty",
  },
  {
    name: "Raja Morifat Hussain",
    role: "TGT",
    qualification: "M.Sc. Zoology, B.Ed.",
    group: "faculty",
  },
  {
    name: "Reshma",
    role: "Art and Craft Teacher",
    qualification: "Bachelor's in Theatre (BTA)",
    group: "faculty",
  },
  {
    name: "Roof Ahmad",
    role: "TGT",
    qualification: "B.Sc. Science",
    group: "faculty",
  },
  {
    name: "Sadaf Abdullah",
    role: "Mother Teacher",
    qualification: "M.Sc. Zoology, B.Ed.",
    group: "faculty",
  },
  {
    name: "Sadiya Farooq",
    role: "TGT",
    qualification: "BCA, MCA, PGDEMA",
    group: "faculty",
  },
  {
    name: "Saima Haji",
    role: "PRT",
    qualification: "B.A., B.Ed.",
    group: "faculty",
  },
  {
    name: "Sameena",
    role: "Mother Teacher",
    qualification: "M.Sc. Maths, B.Ed.",
    group: "faculty",
  },
  {
    name: "Sameena Sultan Tantray",
    role: "PRT",
    qualification: "M.A., B.Ed.",
    group: "faculty",
  },
  {
    name: "Sehrish Bashir",
    role: "Mother Teacher",
    qualification: "M.A. Anthropology",
    group: "faculty",
  },
  {
    name: "Shabina Bano",
    role: "PRT",
    qualification: "M.A. Hindi, M.Ed.",
    group: "faculty",
  },
  {
    name: "Sheikh Daraksha",
    role: "Mother Teacher",
    qualification: "PG History, B.Ed.",
    group: "faculty",
  },
  {
    name: "Suhail Ahmed Khan",
    role: "TGT",
    qualification: "M.A. Urdu, PGDUG",
    group: "faculty",
  },
  {
    name: "Sumaya Ayoub",
    role: "Mother Teacher",
    qualification: "M.Sc. Home Science",
    group: "faculty",
  },
  {
    name: "Sumaya Showkat",
    role: "Counsellor and Wellness Teacher",
    qualification: "M.A. Psychology, PG Guidance & Counselling",
    group: "faculty",
  },
  {
    name: "Sumiya Mushtaq",
    role: "PRT",
    qualification: "M.A. Political Science, B.Ed., UGC NET",
    group: "faculty",
  },
  {
    name: "Tabinda Javeed",
    role: "PRT",
    qualification: "M.A. English, B.Ed., NET, GATE, CTET",
    group: "faculty",
  },
  {
    name: "Tania Shah",
    role: "Mother Teacher",
    qualification: "M.A. English, B.Ed.",
    group: "faculty",
  },
  {
    name: "Zahid Rashid",
    role: "Robotics Teacher",
    qualification: "B.Tech (E&C)",
    group: "faculty",
  },
  {
    name: "Zainab Amin",
    role: "PRT",
    qualification: "M.Sc. Food Science & Clinical Nutrition",
    group: "faculty",
  },
  {
    name: "Zainab Barkat Ali",
    role: "PRT",
    qualification: "M.Sc. Zoology, M.Sc. Anthropology",
    group: "faculty",
  },
];
